name: fn_file_manager
description: "FN File Manager - Cross-platform file manager."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  ffi: ^2.1.4
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  file_selector: ^1.1.0
  crypto: ^3.0.7
  image: ^4.9.1

  # Video player
  fvp: ^0.38.1
  video_player: ^2.14.0
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

  # New features
  share_plus: ^13.3.0
  flutter_markdown: ^0.7.7+1
  pdfx: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^20.1.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/

