/// utils.c - 通用工具函数
#include "bridge_api.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char b64_table[] =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";

char *utils_base64_encode(const unsigned char *data, int len, int *out_len) {
    if (!data || len < 0) return NULL;
    int olen = 4 * ((len + 2) / 3);
    char *b64 = (char *)malloc(olen + 1);
    if (!b64) return NULL;
    int i = 0, j = 0;
    while (i < len) {
        unsigned int a = i < len ? data[i++] : 0;
        unsigned int b = i < len ? data[i++] : 0;
        unsigned int c = i < len ? data[i++] : 0;
        unsigned int triple = (a << 16) | (b << 8) | c;
        b64[j++] = b64_table[(triple >> 18) & 0x3F];
        b64[j++] = b64_table[(triple >> 12) & 0x3F];
        b64[j++] = (i > len + 1) ? '=' : b64_table[(triple >> 6) & 0x3F];
        b64[j++] = (i > len) ? '=' : b64_table[triple & 0x3F];
    }
    b64[j] = '\0';
    if (out_len) *out_len = olen;
    return b64;
}

char *utils_strdup(const char *s) {
    if (!s) return NULL;
    size_t n = strlen(s) + 1;
    char *d = (char *)malloc(n);
    if (d) memcpy(d, s, n);
    return d;
}

unsigned char *utils_read_file(const char *path, int *out_len) {
    if (!path) return NULL;
    FILE *f = fopen(path, "rb");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (size <= 0) { fclose(f); return NULL; }
    unsigned char *buf = (unsigned char *)malloc((size_t)size);
    if (!buf) { fclose(f); return NULL; }
    size_t rd = fread(buf, 1, (size_t)size, f);
    fclose(f);
    if (rd != (size_t)size) { free(buf); return NULL; }
    if (out_len) *out_len = (int)size;
    return buf;
}

char *utils_error_json(const char *msg) {
    size_t len = strlen(msg) + 64;
    char *json = (char *)malloc(len);
    snprintf(json, len, "{\"error\":\"%s\"}", msg);
    return json;
}

void bridge_free_string(char *str) {
    if (str) free(str);
}

// ── GPU 硬件解码能力检测 ──

#if defined(__linux__)

#include <stdio.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>

/// 检测 /dev/dri 是否有 GPU 设备
static int detect_dri_gpu(void) {
    DIR *dir = opendir("/dev/dri");
    if (!dir) return 0;
    int count = 0;
    struct dirent *ent;
    while ((ent = readdir(dir)) != NULL) {
        if (strncmp(ent->d_name, "card", 4) == 0) count++;
    }
    closedir(dir);
    return count;
}

/// 检测是否运行在 ZINK 软件渲染（无真实GPU）
static int detect_zink_software(void) {
    FILE *f = popen("glxinfo 2>/dev/null | head -30", "r");
    if (!f) return 1; // 无法检测，保守返回"软件渲染"
    char line[256];
    int is_software = 0;
    while (fgets(line, sizeof(line), f)) {
        if (strstr(line, "llvmpipe") || strstr(line, "ZINK") || strstr(line, "Software")) {
            is_software = 1;
            break;
        }
    }
    pclose(f);
    return is_software;
}

/// 检测 Vulkan 驱动是否可用
static int detect_vulkan_driver(void) {
    FILE *f = popen("vulkaninfo 2>/dev/null | grep 'driverName'", "r");
    if (!f) return 0;
    char line[256];
    int found = 0;
    while (fgets(line, sizeof(line), f)) {
        if (strstr(line, "driverName") && !strstr(line, "llvmpipe")) {
            found = 1;
            break;
        }
    }
    pclose(f);
    return found;
}

#endif // __linux__

/// 检测GPU硬件解码能力，返回JSON:
/// {"hw_decode": true/false, "gpu": "nvidia"/"mesa"/"zink"/"none", "recommendation": "auto"/"no"}
char *gpu_detect_hw_decode(void) {
    char gpu_name[64] = "unknown";
    int hw_ok = 0;

#if defined(__linux__)
    int dri = detect_dri_gpu();
    if (dri == 0) {
        strcpy(gpu_name, "none");
        hw_ok = 0;
    } else if (detect_zink_software()) {
        strcpy(gpu_name, "zink");
        hw_ok = 0;
    } else if (detect_vulkan_driver()) {
        strcpy(gpu_name, "vulkan");
        hw_ok = 1;
    } else {
        // 有DRI设备但无Vulkan驱动 → 保守用软解，auto-safe在ZINK下会断言失败
        strcpy(gpu_name, "mesa-nohw");
        hw_ok = 0;
    }
#elif defined(__ANDROID__)
    strcpy(gpu_name, "android");
    hw_ok = 1; // Android通常有硬件解码
#else
    strcpy(gpu_name, "unknown");
    hw_ok = 0;
#endif

    const char *recommendation = hw_ok ? "auto-safe" : "no";

    // 写入 mpv.conf 让 mpv 启动时自动读取 hwdec 配置
#if defined(__linux__)
    {
        const char *home = getenv("HOME");
        if (home) {
            char dir[512];
            snprintf(dir, sizeof(dir), "%s/.config/mpv", home);
            char cmd[600];
            snprintf(cmd, sizeof(cmd), "mkdir -p \"%s\"", dir);
            system(cmd);
            char path[600];
            snprintf(path, sizeof(path), "%s/mpv.conf", dir);
            FILE *f = fopen(path, "w");
            if (f) {
                fprintf(f, "# Auto-generated by file manager (GPU: %s)\n", gpu_name);
                fprintf(f, "hwdec=%s\n", recommendation);
                fclose(f);
            }
        }
    }
#endif

    size_t sz = 256;
    char *json = (char *)malloc(sz);
    snprintf(json, sz, "{\"hw_decode\":%s,\"gpu\":\"%s\",\"recommendation\":\"%s\"}",
             hw_ok ? "true" : "false", gpu_name, recommendation);
    return json;
}
